### ISSUE TITLE
Highlight the keywords in URL of docs search results

### ISSUE THREAD

**Issue by lilin90** [pingcap/website-docs#104]
**Background:** When you search a keyword, sometimes you may ignore the exact result, because the keyword is not so friendly highlighted. For example: When you search `general log` from [docs.pingcap.com](https://docs.pingcap.com/tidb/stable), the second result is right the one. But users can miss it because the keyword is not highlighted, as shown below:

![image](https://user-images.githubusercontent.com/30922556/91515205-345b2a00-e91b-11ea-8923-d98521b5dae5.png)

**Requirement:** Make the keywords stand out, more easily to see by highlighting words or other methods suggested by FE

**Scope:** Both English and Chinese documentation

@YiniXu9506 PTAL~ Thanks!

**Comment by YiniXu9506** [comment]
The keywords on URL cannot be highlight. The element does not returned by Algolia, it's hard and complicate to highlight this element.
