### ISSUE TITLE
Change the contact us button

### ISSUE THREAD

**Issue by ran-huang** [pingcap/website-docs#125]
In the English docs website, the `Contact us` button is currently `mailto:info@pingcap.com`.
We hope this button can direct users to the [Contact us page](https://pingcap.com/contact-us/).
![image](https://user-images.githubusercontent.com/59654584/98508100-d8f1d480-2299-11eb-83f7-3a51d85c9f8a.png)

**Comment by lilin90** [comment]
Yes, **only** the English version. For Chinese pages, just keep it as the email.

**Comment by ran-huang** [comment]
@dcalvin FYI~
