### ISSUE TITLE
Change the language button

### ISSUE THREAD

**Issue by CharLotteiu** [pingcap/website-docs#127]
Currently, the `language` button at the foot of our documentation website only supports to jump to the home page of the other language. 
We hope that by clicking this button, user can jump to the other language version of the current page . If the current page doesn't have a corresponding page in another language, we can prompt certain messages and then direct users to the home page.
![image](https://user-images.githubusercontent.com/37295236/98922913-fdee7d80-250d-11eb-9130-5a7a09f33112.png)

**Comment by lilin90** [comment]
@CharLotteiu Thanks for following up!

**Comment by YiniXu9506** [comment]
@lilin90 @CharLotteiu The feature almost done, please determine the tips to let user understand whether the doc exists on different languages or not.

**Comment by YiniXu9506** [comment]
From @CharLotteiu 

中文文案：暂未提供本页面对应的中文页面
英文文案：The English version of this page is temporarily not available.

TiDB Cloud 文档特殊的中文文案：暂不提供 TiDB Cloud 中文文档
