### ISSUE TITLE
Move the language button

### ISSUE THREAD

**Issue by tisonkun** [pingcap/website-docs#131]
Currently the language button lives at footer. However, it is quite indirectly to user to find it.

Both [Pulsar doc site](http://pulsar.apache.org/docs/en/concepts-messaging/) and [Flink doc site](https://flink.apache.org/) displays the language button at the nav bar so that we can always find the button at an obvious place. It would be more user-friendly if tidb docs align with them.

**Comment by YiniXu9506** [comment]
@TisonKun Thanks for you feedback. I will let you know after discussion with @lilin90 

Hi @lilin90 , do you want to move the language button?

**Comment by lilin90** [comment]
@YiniXu9506 For the language button, [docs.pingcap.com](https://docs.pingcap.com/tidb/stable) uses a similar position to that of [pingcap.com](https://en.pingcap.com/). We'll determine after knowing more about users' needs and UI design consideration.

**Comment by YiniXu9506** [comment]
Done in PR #179
