### ISSUE TITLE
Add a version notice to TiDB Operator v1.0 docs

### ISSUE THREAD

**Issue by ran-huang** [pingcap/website-docs#151]
TiDB Operator v1.0 docs are no longer actively maintained, and users are recommended to use TiDB Operator v1.1 (stable) directly.
However, currently, because Google search results give more weight to v1.0 docs than v1.1, and we don't provide an obvious notice in v1.0 docs, some users are misguided to use v1.0.

So we propose **adding a global version notice to v1.0 docs**. For example:

> **Note:**
>
> You are viewing TiDB Operator v1.0 documentation, which is no longer actively maintained. For the latest stable version, click [here](https://docs.pingcap.com/tidb-in-kubernetes/stable/).

**Comment by ran-huang** [comment]
Some references:
https://docs.confluent.io/5.1.2/schema-registry/index.html
![image](https://user-images.githubusercontent.com/59654584/108672316-d8b1d800-751c-11eb-9646-5a85ec1aead4.png)
https://v1-17.docs.kubernetes.io/docs/concepts/
![image](https://user-images.githubusercontent.com/59654584/108672332-dfd8e600-751c-11eb-91c4-7e99633e3c32.png)
https://docs.openstack.org/newton/index.html
![image](https://user-images.githubusercontent.com/59654584/108672385-eebf9880-751c-11eb-8ba7-45c4d179b4c4.png)

**Comment by lilin90** [comment]
@ran-huang The notice text "You are viewing TiDB Operator v1.0 documentation, which is no longer actively maintained. For the latest stable version, click [here](https://docs.pingcap.com/tidb-in-kubernetes/stable/)." LGTM.

@yikeke What do you think of the notice text?

**Comment by yikeke** [comment]
LGTM

**Comment by ran-huang** [comment]
Chinese text: "您当前浏览的文档版本是 TiDB Operator v1.0，该版本已不再维护。点击[此处](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable)查看最新稳定版本。"

@lilin90 @yikeke PTAL

**Comment by yikeke** [comment]
LGTM

**Comment by YiniXu9506** [comment]
Deprecation note can be previewed here: 
![image](https://user-images.githubusercontent.com/34967660/109130613-e7062b00-778c-11eb-8ef4-38c5c5b2e9e7.png)
![image](https://user-images.githubusercontent.com/34967660/109130642-eec5cf80-778c-11eb-8817-3d49ab707063.png)

**Comment by ran-huang** [comment]
> Deprecation note can be previewed here:
> ![image](https://user-images.githubusercontent.com/34967660/109130613-e7062b00-778c-11eb-8ef4-38c5c5b2e9e7.png)
> ![image](https://user-images.githubusercontent.com/34967660/109130642-eec5cf80-778c-11eb-8817-3d49ab707063.png)

@YiniXu9506 LGTM, thanks!
