### ISSUE TITLE
Improve table output in PDF docs 

### ISSUE THREAD

**Issue by TomShawn** [pingcap/website-docs#162]
**Is your feature request related to a problem? Please describe.**
The tables displayed in the PDF version of the TiDB documentation look unsatisfactory.
![image](https://user-images.githubusercontent.com/41534398/123205845-2fd8b100-d4ed-11eb-90eb-a948f22eb1b0.png)
![image](https://user-images.githubusercontent.com/41534398/123205857-349d6500-d4ed-11eb-91e3-e19225dace56.png)

**Describe the solution you'd like**
Improve the table display in the PDF docs.

**Comment by YiniXu9506** [comment]
Close since this issue is duplicated to issue https://github.com/pingcap/website-docs/issues/186
