### ISSUE TITLE
Sidebar rolls down again even if only switch tab.

### ISSUE THREAD

**Issue by tisonkun** [pingcap/website-docs#163]
**Describe the bug**

Sidebar rolls down again even if only switch tab.

**To Reproduce**

See the gif below.

**Expected behavior**

Sidebar should not roll down again at this case.

**Screenshots**

![origin_img_v2_acc01b87-60b3-4811-bb3a-afbbf6b76f0g](https://user-images.githubusercontent.com/18818196/124467859-ffd1bd80-ddca-11eb-9e51-1c7147aafb26.gif)

**Desktop (please complete the following information):**
 - OS: Darwin MacBook-Pro 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
 - Browser chrome
 - Version Version 91.0.4472.114 (Official Build) (x86_64)

**Additional context**

@gozssky

**Comment by YiniXu9506** [comment]
Done #179
