### ISSUE TITLE
TiDB docs website changes for 

### ISSUE THREAD

**Issue by qiancai** [pingcap/website-docs#164]
**Is your feature request related to a problem? Please describe.**
As a TiDB user, when I access the TiDB docs site, the default version is v5.0 (stable), which is confusing because v5.1 the latest stable version. 

**Describe the solution you'd like**
1. Set the v5.1 docs as the default entrance of the TiDB docs site using the stable URL. 

2. In the version list, update v5.0 (stable) to v5.0.

3. For v2.1, v3.0, and v4.0, update the old version explanation banner to the following. In each banner, please replace v3.1 with the corresponding TiDB version. 

**Chinese:** 
**重要：**
你正在查看 TiDB 数据库的较旧版本 (TiDB v3.1) 的文档。如无特殊需求，建议使用 TiDB 数据库的[最新稳定版本](https://docs.pingcap.com/tidb/stable)。

**English:**

**Important:**
You are viewing the documentation of an older version of the TiDB database (TiDB v3.1). It is recommended that you use [the latest stable version](https://docs.pingcap.com/zh/tidb/stable) of the TiDB database.

4. For the TiDB docs, except the Dev version, remove the "修改文本"/"Edit this page" link from the upper-right corner. 

**Describe alternatives you've considered**

**Additional context**

**Comment by YiniXu9506** [comment]
[DONE]: item2, item3, item4. 

@qiancai PTAL
