### ISSUE TITLE
 "Was this page helpful" area covers some section titles in the "What's on this page" pane

### ISSUE THREAD

**Issue by qiancai** [pingcap/website-docs#165]
**Describe the bug**
For a document page with a lot of section titles, some titles in the "What's on this page" pane are covered by the  "Was this page helpful" area. 

**To Reproduce**
1. Go to https://docs.pingcap.com/zh/tidb/stable/tidb-configuration-file.
2. In the "What's on this page" pane, scroll down the section titles.
4. See that some titles in the "What's on this page" pane are covered by the  "Was this page helpful" area. 

**Expected behavior**
The  "Was this page helpful" area should not cover the section titles in the "What's on this page" pane.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Additional context**

**Comment by YiniXu9506** [comment]
Done! 
https://github.com/pingcap/website-docs/commit/d01cfcae1561636ad22ed416fdb2cea906f98cd9
