### ISSUE TITLE
Create a preview website for the refactor-migration-docs branch in pingcap/docs repo

### ISSUE THREAD

**Issue by qiancai** [pingcap/website-docs#167]
**Is your feature request related to a problem? Please describe.**

The TiDB migration PMs are going to refactor the migration docs next week. A lot of doc changes will be made then.

**Describe the solution you'd like**

To avoid the impact on the delivery of the existing docs, a new branch named as refactor-migration-docs is created for the refactoring. During the document refactoring, the PMs need to send the preview website to other related colleagues for feedback and decide the next step, so it is important that we could provide a preview website for this branch.

**Describe alternatives you've considered**

**Additional context**

**Comment by YiniXu9506** [comment]
Using Netlify to preview branch [`refactor-migration-docs`](https://github.com/pingcap/website-docs/tree/yini/refactor-migration-docs)
