### ISSUE TITLE
The cross-section links in tidb-stable-zh-manual.pdf are broken 

### ISSUE THREAD

**Issue by qiancai** [pingcap/website-docs#185]
**Describe the bug**
For https://download.pingcap.org/tidb-stable-zh-manual.pdf, whether you view it online or download it for a local check, you will find that the cross-sections links do not behave normally. 

**To Reproduce**
1. Go to https://download.pingcap.org/tidb-stable-zh-manual.pdf. 
2. For online view, after clicking a cross-section link, you are directed to the TOC page. 
3. Download the PDF for local view. After clicking a cross-section link, there is no response. 

**Expected behavior**
In the document PDF, clicking a cross-section link should take you to the page of the target section.

**Comment by YiniXu9506** [comment]
Has been fixed on PR https://github.com/pingcap/docs-cn/pull/7666
