### ISSUE TITLE
Truncated text in tidb-stable-zh-manual.pdf

### ISSUE THREAD

**Issue by qiancai** [pingcap/website-docs#186]
**Describe the bug**
For all tables in https://download.pingcap.org/tidb-stable-zh-manual.pdf, the alignment is center and the columns are too narrow to show the full text.  As a reader, I could not even see the full text to understand the document. 

**To Reproduce**
1. Go to https://download.pingcap.org/tidb-stable-zh-manual.pdf. 
2. From the left TOC panel, click **部署标准集群** > **规划集群拓扑** > **混合部署拓扑**. 
3. Check the table under **拓扑信息**. 
![image](https://user-images.githubusercontent.com/79440533/143375244-2ab3ec55-9871-45f4-8ae5-4de5d066b5b0.png)

**Expected behavior**
- The tables in tidb-stable-zh-manual.pdf should be left-aligned. 
- The width of the table should fit the page. 
- If a cell contains long text, the cell should wrap the text instead of truncating it.

**Comment by curiousRay** [comment]
@qiancai Didn't get assigned immediately after I commented `/assign`

**Comment by qiancai** [comment]
@curiousRay Sorry for the late response. I've assigned this issue to you manually.

**Comment by qiancai** [comment]
Hi @curiousRay Thanks for taking this issue. 👍

Just would like to let you know that the source code of the PDF template is located in <https://github.com/pingcap/docs-cn/blob/master/templates/template.tex>.  Hence, to update the source code, please create a pull request in [pingcap/doc-cn](https://github.com/pingcap/docs-cn).

**Comment by qiancai** [comment]
And if you need to test the PDF generation, please use the script at [docs-cn/scripts/generate_pdf.sh at master · pingcap/docs-cn](https://github.com/pingcap/docs-cn/blob/master/scripts/generate_pdf.sh).

**Comment by qiancai** [comment]
Hi @curiousRay, we have provided a tutorial for self-service PDF generation. Please check [自助生成 TiDB 文档 PDF 教程](https://github.com/pingcap/docs-cn/blob/master/resources/tidb-pdf-generation-tutorial.md) for more information.

**Comment by curiousRay** [comment]
@qiancai Get it!

**Comment by dveeden** [comment]
I think this might be the same issue: https://github.com/pingcap/docs/issues/15982

For other PDF related issues see https://github.com/pingcap/docs/issues?q=is%3Aopen+is%3Aissue+in%3Atitle+PDF

**Comment by dveeden** [comment]
Maybe switching to another image like https://hub.docker.com/r/pandoc/extra would be good.

**Comment by rpaik** [comment]
👋 @curiousRay,  just a friendly reminder to submit your PR for TiDB Docs Dash by January 12 at 07:59 UTC. 🙏

Please reach out if you have any questions or need any help.

**Comment by curiousRay** [comment]
Raised a PR ([https://github.com/pingcap/docs-cn/pull/16173]()) from the `pingcap/docs-cn` repo.

**Comment by curiousRay** [comment]
> Maybe switching to another image like https://hub.docker.com/r/pandoc/extra would be good.

@dveeden Long time no see~ Just to tell you I've been working on a custom docker image using pandoc/extra. 
See [https://hub.docker.com/r/nightkeeper/doc-build](https://hub.docker.com/r/nightkeeper/doc-build)
