### ISSUE TITLE
v5.4 doc unexpectedly redirect to stable(v6.1)

### ISSUE THREAD

**Issue by shczhen** [pingcap/website-docs#272]
As @yahonda said:
I have a question from our customer about TiDB Documentation.
They are planning to install TiDB 5.4.
Steps to reproduce
1. Open TiDB 5.4 document by web browser
https://docs.pingcap.com/tidb/v5.4
2. Expected result
They can see TiDB 5.4 documentation
3. Actual behavior
It redirects to the https://docs.pingcap.com/tidb/stable which shows TiDB 6.1 documentation.
Unless any version given to the URL like https://docs.pingcap.com/tidb , redirecting to the latest stable(LTS) version looks appropriate
but when the version is specified to the URL like https://docs.pingcap.com/tidb/v5.4 , I expect it shows the version specified by the URL.
I'd like to know any thoughts from the documentation team.

**Comment by shczhen** [comment]
After updated webiste-infra nginx rule, it works now.

**Comment by yahonda** [comment]
Validated the fix.
