### ISSUE TITLE
Two commits fails to trigger docs site update

### ISSUE THREAD

**Issue by Oreoxmt** [pingcap/website-docs#273]
**Describe the bug**
Two commits fails to trigger docs site update.

1. base: **master** https://github.com/pingcap/docs/commit/024a14fe7e8821c2c4cef854ae7279d0a3c4cee4

   - Expected: add 7 docs in **Develop > Reference > Archived Docs**
   - Actual: "Archived Docs" is only available in v6.1, **not in dev**
<img width="777" alt="image" src="https://user-images.githubusercontent.com/60599231/173798195-a8f983b1-86ee-4646-a557-75f9be877a0f.png">
<img width="911" alt="image" src="https://user-images.githubusercontent.com/60599231/173798261-72e5cd98-c120-44cf-a691-af07d9a1ef72.png">

2. base: **release-6.1** https://github.com/pingcap/docs/commit/16b2459ccc9dc428a8574f0d83c1c760d5e7b468

   - Expected: remove the experimental warning of [list-columns-partitioning](https://docs.pingcap.com/tidb/stable/partitioned-table#list-columns-partitioning)
   - Actual: the warning is removed in [dev](https://docs.pingcap.com/tidb/dev/partitioned-table#list-columns-partitioning), but **not in [v6.1](https://docs.pingcap.com/tidb/stable/partitioned-table#list-columns-partitioning)**
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/60599231/173797981-fe826dd5-dd10-4b68-897e-1f665c21fd5f.png">

 <img width="1095" alt="image" src="https://user-images.githubusercontent.com/60599231/173795440-912e49c5-1592-40ee-9943-da611042a3dc.png">

**To Reproduce**
3. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shczhen** [comment]
![dFJ16I8WWb](https://user-images.githubusercontent.com/56986964/173806421-b1de7bf6-bccd-4394-beac-9bf5ed5109aa.jpg)
![Jt4ICmsBkD](https://user-images.githubusercontent.com/56986964/173806450-a297030e-81cc-45ec-b775-eb39a7a0450b.jpg)

As you can see in pictures above, the build queue's order is different from docs repo commit's order.

And doc website build based on previous doc cache.(Which they call "Incrementally build")

I think it's a structural issue, which need to refactor website trigger&build logic.

For temporarily workaround, I will trigger a full build.
