### ISSUE TITLE
Add a banner for TiDB Docs Dash

### ISSUE THREAD

**Issue by likidu** [pingcap/website-docs#455]
Position: top ✅, ~~right sidebar, bottom right corner~~
Link (event page): 
- English: https://www.pingcap.com/event/tidb-docs-dash/
- Chinese: will be published in middle Dec

UI text:
- English: **TiDB Docs Dash 2024 | Jan 9-12 (UTC) | Join us to improve docs and win a prize!**
- Chinese: **2024 TiDB 文档挑战赛｜1/9-1/12｜提 PR 或 Issue 来赢取 Bose 耳机、机械键盘等奖品吧！**

When: 2013-12-21
English: event page ready
Chinese: event page to be published

**Comment by likidu** [comment]
Top banner:

![Image](https://github.com/pingcap/website-docs/assets/575981/aa6a0ebf-b797-4e44-b70b-505c5862b9d2)

**Comment by likidu** [comment]
We will first publish English version. Chinese version will follow after.

**Comment by likidu** [comment]
* Text for English version: **TiDB Docs Dash 2024  |  Jan 9-12 (UTC)  |  Join us to improve docs and win a prize!**
* Banner height: **32px**;
* Background image, align to left, and fill the rest of background with color `#15005B`.(
![Image](https://github.com/pingcap/website-docs/assets/575981/19a2da29-ec55-4c32-8012-34027365d914)

**Comment by lilin90** [comment]
Text for Chinese version: 2024 TiDB 文档挑战赛｜1/9-1/12｜提 PR 或 Issue 来赢取 Bose 耳机、机械键盘等奖品吧！

**Comment by Yuiham** [comment]
> https://github.com/pingcap/website-docs/issues/455#issuecomment-1861744136

Is there a svg background image?
