### ISSUE TITLE
Add a banner for docs satisfaction survey

### ISSUE THREAD

**Issue by likidu** [pingcap/website-docs#456]
Position: the bottom right corner of docs pages
When: after 2024 New Year holiday
- Target date: 2024-01-04
- Planned remove date if everything goes well: 2024-02-09

**Comment by likidu** [comment]
We could reuse the space on the right hand article ToC for this:

![Image](https://github.com/pingcap/website-docs/assets/575981/ac4f8d1e-2ca8-4c55-8a01-955ec01c131a)

**Comment by likidu** [comment]
Add an alternative design about floating pop-up on bottom right corner.

**Comment by likidu** [comment]
Here are two variants of the pop-up banner:

![Image](https://github.com/pingcap/website-docs/assets/575981/b22f40e7-d6cc-46d6-9c25-a17d6b92eb97)
![Image](https://github.com/pingcap/website-docs/assets/575981/bcd050d2-e7e1-4254-9be2-885b7166401f)

**Comment by likidu** [comment]
@lilin90 Please take a look.

**Comment by lilin90** [comment]
Adjusted version by our designer:
<img width="1061" alt="image" src="https://github.com/pingcap/website-docs/assets/30922556/c4494e2a-a83e-4789-b567-934ea4bd2679">

**Comment by Yuiham** [comment]
The PR has been added here.
