### ISSUE TITLE
Add search engine as alternative doc search options

### ISSUE THREAD

**Issue by likidu** [pingcap/website-docs#473]
During new doc search transition period, we can add search engine as alternative option for the doc search. Similar experience to v2ex.com.

**Comment by Yuiham** [comment]
We can add a quick link to Google or Bing to the search component based on the user's URL. For example,

- Google: `https://www.google.com/search?q={Query}+site%3Adocs.pingcap.com%2Ftidbcloud`
- Bing: `https://www.bing.com/search?q={Query}+site%3Adocs.pingcap.com%2Ftidbcloud`

**Comment by likidu** [comment]
Figma: https://www.figma.com/file/WFh5lYlRD4UFowM9NDiE71/TiDB-Cloud-Docs?type=design&node-id=551%3A76&mode=design&t=6KXoO7hPCfo8CU1p-1

**Comment by Yuiham** [comment]
Engineering will start around Apr 23, 2024 and will provide a preview link before the end of April.
