### ISSUE TITLE
 Left navigation pane: long English titles without spaces misalign

### ISSUE THREAD

**Issue by qiancai** [pingcap/website-docs#554]
**Describe the bug**
When viewing long English titles without spaces in the left navigation of the documentation site, the left edge of these titles does not align properly, which is very confusing.

**To Reproduce**
1. Go to https://docs.pingcap.com/tidb/stable/information-schema-referential-constraints. 
2. Check the left navigation pane.

**Expected behavior**
The left edge of titles aligns according to the TOC, regardless of title length.

**Screenshots**

![img_v3_02gj_f8ec58ae-259b-4ac5-8881-218baf2d007g](https://github.com/user-attachments/assets/4f3d45c7-8ada-421c-97c7-0466ef63f0c3)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by Oreoxmt** [comment]
I'd like to share an observation regarding the navigation pane behavior in a previous version of website-docs (https://github.com/pingcap/website-docs/commit/9044798d9c52945427cfecebbae1498eefd609d8). When previewing a document on my local machine, I noticed that the previous version handled these cases correctly:

- Title alignment: all titles were properly aligned to the left edge
- Text overflow: long text entries had proper horizontal scrolling functionality

<img width="552" alt="image" src="https://github.com/user-attachments/assets/51ed97c6-c248-4a6a-81e5-09002ad53fcb">
