### ISSUE TITLE
Optimize the display of icons

### ISSUE THREAD

**Issue by toutdesuite** [pingcap/website-docs#74]
对于已经展开的一级目录，能否图标有所区别？原因是：
- 平时点击有个动态的效果
- 从 database tools 点进来，这里正好是最后一行，看不出来这里已经展开，导致找不到位置
![image](https://user-images.githubusercontent.com/12612867/88371114-00459400-cdc6-11ea-9c69-50debd7d45fe.png)
![image](https://user-images.githubusercontent.com/12612867/88373378-5288b400-cdca-11ea-85e6-21afae87aa56.png)

**Comment by toutdesuite** [comment]
@YiniXu9506 PTAL~

**Comment by YiniXu9506** [comment]
Close this issue since it's duplicate of #72
