### ISSUE TITLE
No toggle display for v3.1/v3.0/v2.1 release notes pages

### ISSUE THREAD

**Issue by TomShawn** [pingcap/website-docs#84]
In the following pages, the navigation menu on the left does not have the toggle display for release notes v3.1/v3.0/v2.1:

+ https://docs.pingcap.com/tidb/v3.1/
+ https://docs.pingcap.com/tidb/v3.0/
+ https://docs.pingcap.com/tidb/v2.1/

![image](https://user-images.githubusercontent.com/41534398/89155121-cf6e1780-d59a-11ea-98b5-9af8a3161841.png) ![image](https://user-images.githubusercontent.com/41534398/89155148-de54ca00-d59a-11ea-9ed5-51aa548fd862.png)

**Comment by YiniXu9506** [comment]
@TomShawn It is not correct to add text link right after the level which want to be collapsable. 
![image](https://user-images.githubusercontent.com/34967660/89555943-41688a00-d843-11ea-9da3-1eb1580356ee.png)

Please refer the format of `releases` level in master [TOC.md](https://raw.githubusercontent.com/pingcap/docs/master/TOC.md)

**Comment by TomShawn** [comment]
@YiniXu9506 Thanks! This issue is resolved in https://github.com/pingcap/docs/pull/3575.
