### ISSUE TITLE
Add 6 YouTube videos to TiDB Cloud product & docs pages

### ISSUE THREAD

**Issue by lilin90** [pingcap/website-docs#91]
Video links: https://www.youtube.com/watch?v=MhUVadAOGxc&list=PLlGz8dzgfp-63cXUecHfCoFvMgbxlYaSD&index=1
Related issue: https://github.com/pingcap/website/issues/203

@YiniXu9506 Please help add these videos to TiDB Cloud product & docs pages. Thanks!

**Comment by lilin90** [comment]
Detailed requirements:
1. 直接嵌入 YouTube 视频，不自己托管。
2. 支持点击全屏或退出全屏播放。 
3. 支持分享，但禁用底部的视频推荐即“更多视频”部分。 
4. 去掉边缘的黑色渐变。

**Comment by YiniXu9506** [comment]
See more details on [Jira](https://internal.pingcap.net/jira/browse/INCS-267)

**Comment by YiniXu9506** [comment]
@lilin90 @dcalvin Please help to update the video posters with ratio W:H = 16:9 for all videos.

**Comment by YiniXu9506** [comment]
@lilin90 @dcalvin The 5 videos has been added to the corresponding dbaas docs. PTAL.

**Comment by lilin90** [comment]
LGTM. Thanks a lot! @YiniXu9506
