### ISSUE TITLE
Support displaying the PingCAP logo for docs Tweets

### ISSUE THREAD

**Issue by lilin90** [pingcap/website-docs#98]
Currently, the Tweet about a document at the docs.pingcap.com can't display the logo, as shown in https://twitter.com/PingCAP/status/1295783355628257282. It would be better to display the PingCAP logo. @YiniXu9506 PTAL~ Thanks!
![image](https://user-images.githubusercontent.com/30922556/90846925-e59e1500-e39b-11ea-94c0-1c92ad025ca4.png)

**Comment by YiniXu9506** [comment]
@lilin90 The PingCAP logo has been showed on twitter summary card. PTAL
![image](https://user-images.githubusercontent.com/34967660/91029545-7c373400-e631-11ea-9330-e1b36e055634.png)
